/* A signal is generated by an asynchronous signal handler (7.14.1.1). */

#include <signal.h>
#include <stdlib.h>

int *p = 0;

void sigsig(int sig)
{
	signal(SIGSEGV, sigsig);
	*p = 0;
}

int main(void)
{
	signal(SIGSEGV, sigsig);
	*p = 0;
}
