/* A signal is generated by an asynchronous signal handler (7.14.1.1). */

#include <signal.h>
#include <stdlib.h>

int n;

void sigsig(int sig)
{
	n = sig / atoi("0");
}

int main(void)
{
	signal(SIGSEGV, sigsig);
	int *p = 0;
	*p = 0;
}
